databases:
  - name: mysite
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: englishchater
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn englishchater.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: WEB_CONCURRENCY
        value: 4